# fly.toml app configuration file generated for monitor-divine-bush-8898 on 2025-02-02T22:42:03+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'monitor-divine-bush-8898'
primary_region = 'arn'
kill_signal = 'SIGTERM'

[build]

[env]
  PHX_HOST = 'monitor-divine-bush-8898.fly.dev'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 1000

[[vm]]
  size = 'shared-cpu-1x'
